server:
  port: 8080
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: Membership details
    version: 1.0.0
  main:
    banner-mode: off
application:
  version: v1
  caches:
    user-details-cache: user-details
    membership-result-cache: membership-details
logging:
  level:
    web: debug