
server:
  port: ${APP_PORT:8080}
  error:
    whitelabel:
      enabled: false
spring:
  application:
    name: MembershipDetails
    version: 1.0.0
  main:
    banner-mode: off
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KC_CONTAINER_NAME:localhost}:${KC_PORT:8100}/realms/app_realm/protocol/openid-connect/certs

application:
  version: v1
  caches:
    user-details-cache: user-details
    membership-result-cache: membership-details

keycloak:
  id: keycloak
  host: ${KC_HOST:localhost}
  port: ${KC_PORT:8100}
  admin-username: ${KC_ADMIN_USERNAME:admin}
  admin-password: ${KC_ADMIN_PASSWORD:password}
  client-id: keycloak-auth-client
  grant-type: client_credentials
  admin-token-path: /realms/master/protocol/openid-connect/token
  clients-settings-path: /admin/realms/app_realm/clients
  realm-auth-uri: /realms/app_realm/protocol/openid-connect/auth
  client-scope: app_client